#!/bin/sh

for i in 1 2 3 4 5 6 7
do
	echo "****************"
	zcc "t$i"
	echo "****************"
done
for i in 1 2 3
do
	echo "****************"
	zcc "test$i"
	echo "****************"
done
echo "Printing Big and Bad"
echo ""
echo "*************"
echo "Big"
zcc eBig
echo "*************"
echo "Bad"
zcc eBad
echo "*************"
